openapi: 3.2.0
info:
  description: API to send emails with Mandrill
  version: 1.0.0
  title: email Personal Hooks API
servers:
- url: /mail
tags:
- name: personalHooks
paths:
  /api/v1/signupSelfValidation:
    post:
      tags:
      - personalHooks
      summary: send signupSelfValidation email
      description: ''
      operationId: signupSelfValidation
      security:
      - Authorization: []
      parameters:
      - $ref: '#/components/parameters/BrandId'
      - $ref: '#/components/parameters/UserId'
      responses:
        '200':
          $ref: '#/components/responses/Success'
        '500':
          $ref: '#/components/responses/InternalError'
components:
  parameters:
    UserId:
      name: userId
      in: formData
      description: id from /api/v1/users/me
      required: true
      type: string
    BrandId:
      name: brandId
      in: formData
      description: digital, up, onboarding etc.
      type: string
      required: true
  responses:
    Success:
      description: Email sent successfully
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: object
                properties:
                  ResponseMetadata:
                    type: object
                    properties:
                      RequestId:
                        type: string
                  MD5OfMessageBody:
                    type: string
                  MessageId:
                    type: string
    InternalError:
      description: InternalError
      content:
        application/json:
          schema:
            type: string
  securitySchemes:
    Authorization:
      type: apiKey
      name: Authorization
      in: header
