openapi: 3.2.0
info:
  description: API to send emails with Mandrill
  version: 1.0.0
  title: email Review API
servers:
- url: /mail
tags:
- name: review
paths:
  /api/v1/skillToReview:
    post:
      tags:
      - review
      summary: send skill to review email
      description: send skill to review email
      security:
      - Authorization: []
      parameters:
      - $ref: '#/components/parameters/UserId'
      - $ref: '#/components/parameters/SkillRef'
      responses:
        '200':
          $ref: '#/components/responses/Success'
        '500':
          $ref: '#/components/responses/InternalError'
components:
  parameters:
    SkillRef:
      name: data[skillRef]
      in: formData
      required: true
      type: string
    UserId:
      name: userId
      in: formData
      description: id from /api/v1/users/me
      required: true
      type: string
  responses:
    Success:
      description: Email sent successfully
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: object
                properties:
                  ResponseMetadata:
                    type: object
                    properties:
                      RequestId:
                        type: string
                  MD5OfMessageBody:
                    type: string
                  MessageId:
                    type: string
    InternalError:
      description: InternalError
      content:
        application/json:
          schema:
            type: string
  securitySchemes:
    Authorization:
      type: apiKey
      name: Authorization
      in: header
