openapi: 3.2.0
info:
  description: API to send emails with Mandrill
  version: 1.0.0
  title: email Mobile API
servers:
- url: /mail
tags:
- name: Mobile
paths:
  /api/v1/mobileConnection:
    post:
      tags:
      - Mobile
      summary: send mobileConnection email
      description: ''
      security:
      - Authorization: []
      parameters:
      - $ref: '#/components/parameters/RecipientAddress'
      responses:
        '200':
          $ref: '#/components/responses/Success'
        '500':
          $ref: '#/components/responses/InternalError'
      operationId: postApiV1MobileConnection
      x-operation-id-source: derived
components:
  responses:
    InternalError:
      description: InternalError
      content:
        application/json:
          schema:
            type: string
    Success:
      description: Email sent successfully
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: object
                properties:
                  ResponseMetadata:
                    type: object
                    properties:
                      RequestId:
                        type: string
                  MD5OfMessageBody:
                    type: string
                  MessageId:
                    type: string
  parameters:
    RecipientAddress:
      name: recipientAddress
      in: formData
      description: an address mail
      required: true
      type: string
  securitySchemes:
    Authorization:
      type: apiKey
      name: Authorization
      in: header
